# Use the official ROS 2 jazzy base image
FROM osrf/ros:jazzy-desktop-full

# Install additional dependencies if needed
RUN apt-get update && apt-get install -y \
    nano \
    terminator \
    && rm -rf /var/lib/apt/lists/*

# Create a ROS 2 workspace
WORKDIR /ros2_ws
RUN mkdir -p src

# Source the ROS 2 setup script in the .bashrc
RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc

# Set the entrypoint
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]